name: GitHub CI/CD Pipeline for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci
        
      - name: Run Tests
        run: npm test --if-present

      - name: Build Project
        run: npm run build
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: './dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write      # Required to deploy pages
      id-token: write   # Required to authenticate with GitHub Pages

     environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
      steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
            
       
